### ISSUE TITLE
Qiime2 Phylo-RPCA ValueError

### ISSUE THREAD

**Issue by AngusBall** [biocore/gemelli#77]
Hello,

Firstly, thanks for making such a cool statistical test! 
Unfortunately, I'm having some troubles running the phylo-RPCA. 

I'm importing my data from DADA2 that's been run through R and have followed [KeyError when attempting phylo-RPCA with Gemelli](https://forum.qiime2.org/t/keyerror-when-attempting-phylo-rpca-with-gemelli/25936). I've specifically looked into the qza artifacts so I don't think its a formatting error (but to be fair I am new to qiime2). Eitherway, when I run the phylo-RPCA I get the following Error:

```
Plugin error from gemelli:

  No requested tips found

Debug info has been saved to /tmp/qiime2-q2cli-err-a24gvsx5.log
```

The Debug info is as follows
```
Traceback (most recent call last):
  File "/home/aball/anaconda/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/q2cli/commands.py", line 520, in __call__
    results = self._execute_action(
  File "/home/aball/anaconda/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/q2cli/commands.py", line 581, in _execute_action
    results = action(**arguments)
  File "<decorator-gen-46>", line 2, in phylogenetic_rpca_with_taxonomy
  File "/home/aball/anaconda/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/qiime2/sdk/action.py", line 342, in bound_callable
    outputs = self._callable_executor_(
  File "/home/aball/anaconda/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/qiime2/sdk/action.py", line 566, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/home/aball/anaconda/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/gemelli/rpca.py", line 82, in phylogenetic_rpca_with_taxonomy
    output = phylogenetic_rpca(table=table,
  File "/home/aball/anaconda/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/gemelli/rpca.py", line 252, in phylogenetic_rpca
    phylogeny = bp_read_phylogeny(table,
  File "/home/aball/anaconda/envs/qiime2-amplicon-2023.9/lib/python3.8/site-packages/gemelli/preprocessing.py", line 270, in bp_read_phylogeny
    phylogeny = phylogeny.shear(names_to_keep).collapse()
  File "bp/_bp.pyx", line 758, in bp._bp.BP.shear
  File "bp/_bp.pyx", line 800, in bp._bp.BP.shear
ValueError: No requested tips found
```

I've found a similar error in [Greengenes2 taxonomy's](https://forum.qiime2.org/t/greengenes2-taxonomy-from-features-error/25994) forums, but I didn't see an obvious connection to this code.

Here are the various qiime2 artifacts i'm using:
[Qiime2inputartifacts.zip](https://github.com/biocore/gemelli/files/13852256/Qiime2inputartifacts.zip)

and the qiime2 code
```
# For the phylogenetic tree
qiime phylogeny align-to-tree-mafft-fasttree \
 --i-sequences rep-seqs.qza \
 --o-alignment aligned-rep-seqs.qza \
 --o-masked-alignment masked-aligned-rep-seqs.qza \
 --o-tree unrooted-tree.qza \
 --o-rooted-tree rooted-tree.qza \
 --p-n-threads 14

#for the phylo-RPCA
qiime gemelli phylogenetic-rpca-with-taxonomy \
    --i-table ts_feature-table.qza \
    --i-phylogeny rooted-tree.qza \
    --m-taxonomy-file taxonomy.qza \
    --p-min-feature-count 10 \
    --p-min-sample-count 500 \
    --o-biplot phylo-ordination.qza \
    --o-distance-matrix phylo-distance.qza \
    --o-counts-by-node-tree phylo-tree.qza \
    --o-counts-by-node phylo-table.qza \
    --o-t2t-taxonomy phylo-taxonomy.qza
```

Thanks in advance!
Angus

**Comment by cameronmartino** [comment]
Hi @AngusBall,

Thanks for the kind words and for using the tools!

That error means there are no IDs mapping between the tree tips and the features in your table. I took a look and it seems that your table is just transposed. So the features and samples were flipped, thus no overlap. I transposed it and ran it and everything ran fine for me: [Qiime2inputartifacts.zip](https://github.com/biocore/gemelli/files/13877315/Qiime2inputartifacts.zip)


Closing this issue but feel free to re-open it if the problem persists for you. 

Thanks,

Cameron
