### ISSUE TITLE
Error trying to do qc-rarefy

### ISSUE THREAD

**Issue by callaband** [biocore/gemelli#80]
Okay, trying to run qc-rarefy in qiime2-2023.5 using CLI:
```
qiime gemelli qc-rarefy \
    --i-table feature-table.qza \
    --i-rarefied-distance RPCA-rarefy-distance.qza \
    --i-unrarefied-distance RPCA-dm.qza \
    --o-visualization RPCA-rarefy-qc.qzv
```
Get this Error:
```
 Plugin error from gemelli:

  [Errno 2] No such file or directory: '/Users/miniforge3/envs/qiime2-2023.5/lib/python3.8/site-packages/gemelli/q2/qc_assests/index.html'

Debug info has been saved to random.log
```
Log file: 
```
Traceback (most recent call last):
  File "/Users/miniforge3/envs/qiime2-2023.5/lib/python3.8/site-packages/q2cli/commands.py", line 468, in __call__
    results = action(**arguments)
  File "<decorator-gen-88>", line 2, in qc_rarefy
  File "/Users/miniforge3/envs/qiime2-2023.5/lib/python3.8/site-packages/qiime2/sdk/action.py", line 274, in bound_callable
    outputs = self._callable_executor_(
  File "/Users/miniforge3/envs/qiime2-2023.5/lib/python3.8/site-packages/qiime2/sdk/action.py", line 558, in _callable_executor_
    ret_val = self._callable(output_dir=temp_dir, **view_args)
  File "/Users/miniforge3/envs/qiime2-2023.5/lib/python3.8/site-packages/gemelli/q2/_visualizer.py", line 83, in qc_rarefy
    q2templates.render(index, output_dir, context=context)
  File "/Users/miniforge3/envs/qiime2-2023.5/lib/python3.8/site-packages/q2templates/_templates.py", line 44, in render
    with open(source_file, 'r') as fh:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/miniforge3/envs/qiime2-2023.5/lib/python3.8/site-packages/gemelli/q2/qc_assests/index.html'
```

I tried to do `pip install gemelli --upgrade` again, in case I missed an update, but no luck.

**Comment by callaband** [comment]
Okay, after a restart of my machine, appears to not have this error anymore. 

But, now I have the issue that when I rarify and drop some of the samples I am getting an error that 1 sample is not present in the dissimilary matrix. But, I'm a little confused since I expect there to be more than 1 samples dropped by rarefaction, which could cause this error, but not a single sample. 

Example:
```
Traceback (most recent call last):
  File "/Users/miniforge3/envs/qiime2-2023.5/lib/python3.8/site-packages/q2cli/commands.py", line 468, in __call__
    results = action(**arguments)
  File "<decorator-gen-88>", line 2, in qc_rarefy
  File "/Users/miniforge3/envs/qiime2-2023.5/lib/python3.8/site-packages/qiime2/sdk/action.py", line 274, in bound_callable
    outputs = self._callable_executor_(
  File "/Users/miniforge3/envs/qiime2-2023.5/lib/python3.8/site-packages/qiime2/sdk/action.py", line 558, in _callable_executor_
    ret_val = self._callable(output_dir=temp_dir, **view_args)
  File "/Users/miniforge3/envs/qiime2-2023.5/lib/python3.8/site-packages/gemelli/q2/_visualizer.py", line 37, in qc_rarefy
    samp_sum_dist) = _qc_rarefaction(table,
  File "/Users/miniforge3/envs/qiime2-2023.5/lib/python3.8/site-packages/gemelli/utils.py", line 104, in qc_rarefaction
    rarefied_distance = rarefied_distance.filter(unrarefied_distance.ids)
  File "/Users/miniforge3/envs/qiime2-2023.5/lib/python3.8/site-packages/skbio/stats/distance/_base.py", line 415, in filter
    idxs = [self.index(id_) for id_ in ids]
  File "/Users/miniforge3/envs/qiime2-2023.5/lib/python3.8/site-packages/skbio/stats/distance/_base.py", line 415, in <listcomp>
    idxs = [self.index(id_) for id_ in ids]
  File "/Users/miniforge3/envs/qiime2-2023.5/lib/python3.8/site-packages/skbio/stats/distance/_base.py", line 340, in index
    raise MissingIDError(lookup_id)
skbio.stats.distance._base.MissingIDError: The ID '15108.2872.WT.sub2.4mo.fecal' is not in the dissimilarity matrix.
```

**Comment by cameronmartino** [comment]
If you are using QIIME2, after an update or installation, you need to do:

```
qiime dev refresh-cache
```

That might be the need for the restart.

For the sample matching, the distance matrices should be matched (or have the same samples) before running the command. Ideally, RPCA will be run on a table with the same samples without rarefaction and with and then the output distances compared. So the protocol would be:

1. Rarefy Table X to get table X_rarefy
2. Run RPCA on X_rarefy to get Distance_rarefy
3. Remove the samples in X not in X_rarefy to get X_subset
4. Run the qc-rarefy command with X_subset and Distance_rarefy.
