### ISSUE TITLE
TEMPTED Error 

### ISSUE THREAD

**Issue by callaband** [biocore/gemelli#92]
Using gemelli (0.0.11)with CLI Qiime2 (2023.5). Running my raw counts table after clr tranform
```
qiime gemelli tempted-factorize \
    --i-table clr-table.qza \
    --m-sample-metadata-file metadata_cleaned.txt \
    --p-individual-id-column 'host_subject_id' \
    --p-state-column 'host_age' \
    --o-individual-biplot tempted/individual_biplot.qza \
    --o-state-loadings tempted/state_loadings.qza \
    --o-distance-matrix tempted/distance_matrix.qza \
    --o-svd-center tempted/svd_center.qza
```
Getting this error: 
```
Plugin error from gemelli:

  Table contains np.nan or missing post transformation.
```
Log File:
```
Traceback (most recent call last):
  File "/Users/user/miniforge3/envs/qiime2-2023.5-gemelli/lib/python3.8/site-packages/q2cli/commands.py", line 468, in __call__
    results = action(**arguments)
  File "<decorator-gen-36>", line 2, in tempted_factorize
  File "/Users/user/miniforge3/envs/qiime2-2023.5-gemelli/lib/python3.8/site-packages/qiime2/sdk/action.py", line 274, in bound_callable
    outputs = self._callable_executor_(
  File "/Users/user/miniforge3/envs/qiime2-2023.5-gemelli/lib/python3.8/site-packages/qiime2/sdk/action.py", line 509, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/Users/user/miniforge3/envs/qiime2-2023.5-gemelli/lib/python3.8/site-packages/gemelli/tempted.py", line 262, in tempted_factorize
    res_ = tempted(table,
  File "/Users/user/miniforge3/envs/qiime2-2023.5-gemelli/lib/python3.8/site-packages/gemelli/tempted.py", line 472, in tempted
    tensor.construct(table,
  File "/Users/user/miniforge3/envs/qiime2-2023.5-gemelli/lib/python3.8/site-packages/gemelli/preprocessing.py", line 1286, in construct
    self._construct()
  File "/Users/user/miniforge3/envs/qiime2-2023.5-gemelli/lib/python3.8/site-packages/gemelli/preprocessing.py", line 1374, in _construct
    raise ValueError('Table contains np.nan or '
ValueError: Table contains np.nan or missing post transformation.
```
But when I check for nans (export qza as biom, convert to tsv):
```
clr = pd.read_csv('tempted/clr-table/feature-table.tsv', 
                  skiprows=1, sep='\t',index_col=0)
clr.isnull().values.any()
```
Result is False/no nans - so as far as I can tell there are no nans to cause the error, so perhaps something else is missing? RPCA and CTF run on this dataset with no issues. (Thanks for the update, by the way!)

GitHub won't let me attach .qza or .biom files, but happy to send via Slack.

**Comment by cameronmartino** [comment]
This should be fixed in v0.0.12 - feel free to re-open this issue if the problem persists. Thanks for reporting!!
